name: workout-tracker
static_sites:
  - name: workout-tracker
    git:
      branch: master
      repo_clone_url: https://github.com/sandeepreddy3636/first-repo
    source_dir: /
    output_dir: /
    index_document: index.html
    error_document: index.html
    routes:
      - path: /
